#!/usr/bin/env python
# -*- coding: utf-8 -*-

import time
import RPi.GPIO as GPIO
import signal, os
import sys

def handler( signum, frame ):
        """
        Ctrl-Cで呼び出される終了処理。
        LEDが点灯したままにならないようにします。
        """
        print "\ncleanup GPIO"
        GPIO.cleanup()
        sys.exit(0)

# Ctrl-Cを検知する仕組み
signal.signal(signal.SIGINT, handler)

# GPIO 18番を準備
GPIO.setmode(GPIO.BCM)
led = 18
GPIO.setup(led, GPIO.OUT)

# 点滅
while True:
    GPIO.output(led, True)  # 点灯
    time.sleep(2)
    GPIO.output(led, False) # 消灯
    time.sleep(2)

